language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - pytest src/test_*.py --cov=geohash
  - pycodestyle src/*py --ignore=E501
  - aws cloudformation package --template-file cf.yaml --s3-bucket cf-templates-ohq9r4yozcyg-us-east-1 --output-template-file out.yaml
  - aws cloudformation deploy --template-file out.yaml --stack-name enkel-api --capabilities CAPABILITY_IAM
after_success:
  - coveralls
